/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binhnn_project2_facerecognition_Process */

#ifndef _Included_com_binhnn_project2_facerecognition_Process
#define _Included_com_binhnn_project2_facerecognition_Process
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binhnn_project2_facerecognition_Process
 * Method:    detectFace
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_binhnn_project2_1facerecognition_Process_detectFace
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
